server.port: 8081

spring:
  application:
    name: album-service

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: ZWVKL0G50DDPWNDHNLYY
  secretKey: q5CDYo3uQZ9E835KunRe8d4pjCExn2xC/MRas7sr
  bucketName: moviefun

security:
  basic:
    enabled: false